.TH U "1" "March 2016" "" "User Commands"
.SH NAME
u-execute \- Executes commands over a host
.SH SYNOPSIS
.B u-execute
\fOHOST\fR
\fICOMMAND\fR
.SH DESCRIPTION
.PP
Allows the execution of a command in a remote host, giving info about
its result.
.SH AUTHOR
Written by Guillermo Robles
.SH "REPORTING BUGS"
Report all bugs to guillerobles1995@gmail.com
