.TH U "1" "March 2016" "" "User Commands"
.SH NAME
u \- Executes commands over multiple hosts
.SH SYNOPSIS
.B u-ping
\fOHOST\fR
.SH DESCRIPTION
.PP
Pings the given host, giving info about its status.
.SH AUTHOR
Written by Guillermo Robles
.SH "REPORTING BUGS"
Report all bugs to guillerobles1995@gmail.com
