#!/bin/sh
# Author: Guillermo Robles
# 
# Function remote-config from the suite u

# We need to transform the host to consider : in the
# middle of the host (scp breaks)
hostSCP=`echo "$2" | sed -e 's/\([^@]*\)@\(.*\)/\1@[\2]/' -e 's/^\([^@]*\)$/[\1]/'`
scp "$1" "$hostSCP:/tmp/puppet_file.pp"
ssh -n "$2" "puppet apply \"/tmp/puppet_file.pp\""
ssh -n "$2" "rm \"/tmp/puppet_file.pp\""
